Tests for metrics
kyma-project/kyma-environment-broker pull request #564
Opened 2024-03-15 05:57 UTC by ukff

- add broker e2e tests for v2 metrics (operationStats)

2024-03-15 13:03 UTC, piotrmiskiewicz commented on cmd/broker/broker_suite_test.go
> +func NewBrokerSuitTestWithMetrics(t *testing.T, version ...string) *BrokerSuiteTest {
I'd add the handler to the router in all tests, why not. In such case you don't need to create another constructor

2024-03-15 13:43 UTC, jaroslaw-pieszka commented on cmd/broker/metrics_test.go
> +		depSuc := uuid.New().String()
nit: inconsistency between `-Suc` and `-Success` postfixes. 
Could we go with only one?

2024-03-18 07:29 UTC, jaroslaw-pieszka approved these changes

2024-03-18 08:40 UTC, ralikio requested changes
Please fill description.

2024-03-18 10:10 UTC, piotrmiskiewicz commented on internal/process/staged_manager.go
> +	m.publisher.Publish(context.TODO(), OperationCounting{
OperationCounting -> OperationFinished

2024-03-18 10:27 UTC, piotrmiskiewicz approved these changes

2024-03-18 10:28 UTC, merged